from rdflib import Graph, Namespace, RDF, OWL
from rdflib.namespace import RDFS, XSD, DCTERMS

# Load full ontology
full_onto = Graph()
full_onto.parse("original_ontology.ttl", format="turtle")

# Create output graph for sub-ontology
sub_onto = Graph()

# Define namespaces
ERA = Namespace("http://data.europa.eu/949/")
sub_onto.bind("", ERA)  # Default namespace for ':'
sub_onto.bind("owl", OWL)
sub_onto.bind("rdf", RDF)
sub_onto.bind("rdfs", RDFS)
sub_onto.bind("xsd", XSD)
sub_onto.bind("dcterms", DCTERMS)

used_entities = set([
    "http://data.europa.eu/949/contactLineSystem",
    "http://data.europa.eu/949/conditionsAppliedRegenerativeBraking",
    "http://data.europa.eu/949/currentLimitationRequired",
    "http://data.europa.eu/949/energySupplySystemTSICompliant",
    "http://data.europa.eu/949/maxTrainCurrent",
    "http://data.europa.eu/949/permissionChargingElectricEnergyTractionStandstill",
    "http://data.europa.eu/949/conditionalRegenerativeBrake",
    "http://data.europa.eu/949/conditionsChargingElectricEnergyStorage",
    "http://data.europa.eu/949/contactLineSystemType",
    "http://data.europa.eu/949/umax2",
    "http://data.europa.eu/949/trainDetectionSystem",
    "http://data.europa.eu/949/trainDetectionSystemSpecificCheckDocument",
    "http://data.europa.eu/949/flangeLubeRules",
    "http://data.europa.eu/949/frequencyBandsForDetection",
    "http://data.europa.eu/949/maxSandingOutput",
    "http://data.europa.eu/949/maxDistEndTrainFirstAxle",
    "http://data.europa.eu/949/maximumInterferenceCurrent",
    "http://data.europa.eu/949/tdsMaximumMagneticField",
    "http://data.europa.eu/949/requiredSandingOverride",
    "http://data.europa.eu/949/frenchTrainDetectionSystemLimitation",
    "http://data.europa.eu/949/tdsFrenchTrainDetectionSystemLimitation",
    "http://data.europa.eu/949/tsiCompliantSandCharacteristics",
    "http://data.europa.eu/949/tsiCompliantFerromagneticWheel",
    "http://data.europa.eu/949/tsiCompliantMaxDistConsecutiveAxles",
    "http://data.europa.eu/949/tsiCompliantMaxImpedanceWheelset",
    "http://data.europa.eu/949/tsiCompliantMetalFreeSpace",
    "http://data.europa.eu/949/tsiCompliantMetalConstruction",
    "http://data.europa.eu/949/tsiCompliantRSTShuntImpedance",
    "http://data.europa.eu/949/tsiCompliantShuntDevices",
    "http://data.europa.eu/949/tsiCompliantCompositeBrakeBlocks",
    "http://data.europa.eu/949/tsiCompliantSanding",
    "http://data.europa.eu/949/tdsMinAxleLoadVehicleCategory",
    "http://data.europa.eu/949/trainDetectionSystemSpecificCheck",
    #"http://data.europa.eu/949/hasAbstraction",
    "http://data.europa.eu/949/imCode",
    "http://data.europa.eu/949/lineReference",
    "http://data.europa.eu/949/validityEndDate",
    "http://data.europa.eu/949/canonicalURI",
    "http://data.europa.eu/949/validityStartDate",
    "http://data.europa.eu/949/digitalSchematicOverview",
    "http://data.europa.eu/949/opName",
    "http://data.europa.eu/949/tafTAPCode",
    "http://data.europa.eu/949/schematicOverviewOP",
    "http://data.europa.eu/949/hasSchematicOverviewOPDigitalForm",
    "http://data.europa.eu/949/siding",
    "http://data.europa.eu/949/opType",
    "http://data.europa.eu/949/opTypeGaugeChangeover",
    "http://data.europa.eu/949/uopid",
    "http://data.europa.eu/949/lengthOfSectionOfLine",
    "http://data.europa.eu/949/solNature",
    "http://data.europa.eu/949/opEnd",
    "http://data.europa.eu/949/opStart",
    "http://data.europa.eu/949/lineNationalId",
    "http://data.europa.eu/949/verificationSRT",
    "http://data.europa.eu/949/demonstrationSRT",
    "http://data.europa.eu/949/lineReferenceTunnelEnd",
    "http://data.europa.eu/949/tunnelKilometerEnd",
    "http://data.europa.eu/949/endLocation",
    "http://data.europa.eu/949/hasEmergencyPlan",
    "http://data.europa.eu/949/hasEvacuationAndRescuePoints",
    "http://data.europa.eu/949/hasWalkway",
    "http://data.europa.eu/949/rollingStockFireCategory",
    "http://data.europa.eu/949/lengthOfTunnel",
    "http://data.europa.eu/949/nationalRollingStockFireCategory",
    "http://data.europa.eu/949/specialTunnelArea",
    "http://data.europa.eu/949/lineReferenceTunnelStart",
    "http://data.europa.eu/949/tunnelKilometerStart",
    "http://data.europa.eu/949/startLocation",
    "http://data.europa.eu/949/tunnelIdentification",
    "http://data.europa.eu/949/complianceInfTsi",
    "http://data.europa.eu/949/crossSectionArea",
    "http://data.europa.eu/949/dieselThermalAllowed",
    "http://data.europa.eu/949/tunnelDocRef",
    "http://data.europa.eu/949/track",
    "http://data.europa.eu/949/hasElectricShoreSupply",
    "http://data.europa.eu/949/hasExternalCleaning",
    "http://data.europa.eu/949/hasRefuelling",
    "http://data.europa.eu/949/hasSandRestocking",
    "http://data.europa.eu/949/hasToiletDischarge",
    "http://data.europa.eu/949/hasWaterRestocking",
    "http://data.europa.eu/949/gradient",
    "http://data.europa.eu/949/sidingId",
    "http://data.europa.eu/949/minimumVerticalRadius",
    "http://data.europa.eu/949/minimumVerticalRadiusCrest",
    "http://data.europa.eu/949/minimumVerticalRadiusHollow",
    "http://data.europa.eu/949/lengthOfSiding",
    "http://data.europa.eu/949/tenClassification",
    "http://data.europa.eu/949/tenClassificationSiding",
    "http://data.europa.eu/949/tenClassificationPlatformEdge",
    "http://data.europa.eu/949/validityStartDate",
    "http://data.europa.eu/949/validityEndDate",
    "http://data.europa.eu/949/imCode",
    "http://data.europa.eu/949/platformEdge",
    "http://data.europa.eu/949/hasPlatformCurvature",
    "http://data.europa.eu/949/assistanceStartingTrain",
    "http://data.europa.eu/949/platformHeight",
    "http://data.europa.eu/949/platformId",
    "http://data.europa.eu/949/areaBoardingAid",
    "http://data.europa.eu/949/lengthOfPlatform",
    "http://data.europa.eu/949/imCode",
    "http://data.europa.eu/949/bridge",
    "http://data.europa.eu/949/trackDirection",
    "http://data.europa.eu/949/trackId",
    "http://data.europa.eu/949/maximumTrainDeceleration",
    "http://data.europa.eu/949/contactStripMaterial",
    "http://data.europa.eu/949/hotAxleBoxDetectorLocation",
    "http://data.europa.eu/949/trackSystemSeparationInfo",
    "http://data.europa.eu/949/railInclination",
    "http://data.europa.eu/949/dNvovtrp",
    "http://data.europa.eu/949/linesideDistanceIndicationAppearance",
    "http://data.europa.eu/949/gsmROptionalFunctions",
    "http://data.europa.eu/949/hasHotAxleBoxDetector",
    "http://data.europa.eu/949/contactStripMaterialMetallicContent",
    "http://data.europa.eu/949/vNvallowovtrp",
    "http://data.europa.eu/949/hotAxleBoxDetectorIdentification",
    "http://data.europa.eu/949/atoSystemVersion",
    "http://data.europa.eu/949/gprsForETCS",
    "http://data.europa.eu/949/magneticBraking",
    "http://data.europa.eu/949/tNvcontact",
    "http://data.europa.eu/949/hotAxleBoxDetectorTSICompliant",
    "http://data.europa.eu/949/qNvsbtsmperm",
    "http://data.europa.eu/949/cantDeficiencyBasicSSP",
    "http://data.europa.eu/949/etcsLevel",
    "http://data.europa.eu/949/tenGISId",
    "http://data.europa.eu/949/vehicleTypesCompatibleTrafficLoad",
    "http://data.europa.eu/949/etcsTransmittedTrackConditions",
    "http://data.europa.eu/949/freightCorridor",
    "http://data.europa.eu/949/accelerationLevelCrossing",
    "http://data.europa.eu/949/gsmrConstraintsOperateOnlyInCircuitSwitch",
    "http://data.europa.eu/949/tsiPantographHead",
    "http://data.europa.eu/949/bigMetalMass",
    "http://data.europa.eu/949/wheelSetGauge",
    "http://data.europa.eu/949/IdPhoneErtmsRadioBlockCenter",
    "http://data.europa.eu/949/TSITractionHarmonics",
    "http://data.europa.eu/949/osmClass",
    "http://data.europa.eu/949/verificationCCS",
    "http://data.europa.eu/949/demonstrationENE",
    "http://data.europa.eu/949/dataRadioCompatible",
    "http://data.europa.eu/949/vehiclesCompatibleTrafficLoad",
    "http://data.europa.eu/949/hasSystemSeparation",
    "http://data.europa.eu/949/permitUseReflectivePlates",
    "http://data.europa.eu/949/etcsSystemCompatibility",
    "http://data.europa.eu/949/structureCheckLocation",
    "http://data.europa.eu/949/switchRadioSystem",
    "http://data.europa.eu/949/conditionsUseReflectivePlates",
    "http://data.europa.eu/949/minimumWheelDiameter",
    "http://data.europa.eu/949/gsmrErrorCorrectionsOnboard",
    "http://data.europa.eu/949/linesideDistanceIndicationPositioning",
    "http://data.europa.eu/949/maximumContactWireHeight",
    "http://data.europa.eu/949/switchProtectControlWarning",
    "http://data.europa.eu/949/nationalLoadCapability",
    "http://data.europa.eu/949/hasETCSRestrictionsConditions",
    "http://data.europa.eu/949/gaugingProfile",
    "http://data.europa.eu/949/gsmrForcedDeregistrationFunctionalNumber",
    "http://data.europa.eu/949/nationalValuesBrakeModel",
    "http://data.europa.eu/949/gsmRActiveMobiles",
    "http://data.europa.eu/949/localRulesOrRestrictionsDoc",
    "http://data.europa.eu/949/linesideDistanceIndicationFrequency",
    "http://data.europa.eu/949/hasOtherTrainProtection",
    "http://data.europa.eu/949/protectionLegacySystem",
    "http://data.europa.eu/949/eddyCurrentBrakingConditionsDocument",
    "http://data.europa.eu/949/gsmRAdditionalInfo",
    "http://data.europa.eu/949/TSIMagneticFields",
    "http://data.europa.eu/949/documentRestrictionPositionContactLineSeparation",
    "http://data.europa.eu/949/profileNumberSwapBodies",
    "http://data.europa.eu/949/publicNetworkRoamingDetails",
    "http://data.europa.eu/949/hasTSITrainDetection",
    "http://data.europa.eu/949/standardCombinedTransporRollerUnits",
    "http://data.europa.eu/949/minRimWidth",
    "http://data.europa.eu/949/etcsTransmitsTrackConditions",
    "http://data.europa.eu/949/minDistConsecutiveAxles",
    "http://data.europa.eu/949/permittedContactForce",
    "http://data.europa.eu/949/gradientProfile",
    "http://data.europa.eu/949/multipleTrainProtectionRequired",
    "http://data.europa.eu/949/demonstrationINF",
    "http://data.europa.eu/949/redLightsRequired",
    "http://data.europa.eu/949/etcsOptionalFunctions",
    "http://data.europa.eu/949/documentRestrictionPowerConsumption",
    "http://data.europa.eu/949/voiceRadioCompatible",
    "http://data.europa.eu/949/minimumContactWireHeight",
    "http://data.europa.eu/949/vNvsupovtrp",
    "http://data.europa.eu/949/etcsImplementsLevelCrossingProcedure",
    "http://data.europa.eu/949/gaugingTransversalDocument",
    "http://data.europa.eu/949/distSignToPhaseEnd",
    "http://data.europa.eu/949/etcsInfillLineAccess",
    "http://data.europa.eu/949/atoGradeAutomation",
    "http://data.europa.eu/949/mNvcontact",
    "http://data.europa.eu/949/gaugingCheckLocation",
    "http://data.europa.eu/949/etcsInfill",
    "http://data.europa.eu/949/lineCategory",
    "http://data.europa.eu/949/hotAxleBoxDetectorGeneration",
    "http://data.europa.eu/949/legacyRadioSystem",
    "http://data.europa.eu/949/gsmrNetworkCoverage",
    "http://data.europa.eu/949/tiltingSupported",
    "http://data.europa.eu/949/compatibilityProcedureDocument",
    "http://data.europa.eu/949/trackPhaseInfo",
    "http://data.europa.eu/949/hasSevereWeatherConditions",
    "http://data.europa.eu/949/flangeLubeForbidden",
    "http://data.europa.eu/949/mNvderun",
    "http://data.europa.eu/949/additionalBrakingInformationDocument",
    "http://data.europa.eu/949/maximumBrakingDistance101",
    "http://data.europa.eu/949/tsiSwitchCrossing",
    "http://data.europa.eu/949/usesGroup555",
    "http://data.europa.eu/949/standardCombinedTransportContainers",
    "http://data.europa.eu/949/instructionsSwitchRadioSystems",
    "http://data.europa.eu/949/atoCommunicationSystem",
    "http://data.europa.eu/949/otherPantographHead",
    "http://data.europa.eu/949/radioNetworkId",
    "http://data.europa.eu/949/hasBallast",
    "http://data.europa.eu/949/trainIntegrityOnBoardRequired",
    "http://data.europa.eu/949/otherTrainProtection",
    "http://data.europa.eu/949/gprsImplementationArea",
    "http://data.europa.eu/949/magneticBrakingConditionsDocument",
    "http://data.europa.eu/949/maximumTemperature",
    "http://data.europa.eu/949/hotAxleBoxDetectorDirection",
    "http://data.europa.eu/949/ertmsErrorCorrectionsOnBoard",
    "http://data.europa.eu/949/minFlangeHeight",
    "http://data.europa.eu/949/conditionsSwitchClassBSystems",
    "http://data.europa.eu/949/phaseInfo",
    "http://data.europa.eu/949/highSpeedLoadModelCompliance",
    "http://data.europa.eu/949/temperatureRange",
    "http://data.europa.eu/949/etcsDegradedSituation",
    "http://data.europa.eu/949/loadCapability",
    "http://data.europa.eu/949/trackLoadCapability",
    "http://data.europa.eu/949/qNvemrrls",
    "http://data.europa.eu/949/isQuietRoute",
    "http://data.europa.eu/949/cantDeficiency",
    "http://data.europa.eu/949/publicNetworkRoaming",
    "http://data.europa.eu/949/conditionsSwitchTrainProtectionSystems",
    "http://data.europa.eu/949/gsmRNoCoverage",
    "http://data.europa.eu/949/etcsErrorCorrectionsOnboard",
    "http://data.europa.eu/949/etcsSystemFunctionalitiesNextFiveYears",
    "http://data.europa.eu/949/verificationENE",
    "http://data.europa.eu/949/minDistFirstLastAxle",
    "http://data.europa.eu/949/safeConsistLengthInformationNecessary",
    "http://data.europa.eu/949/atoErrorCorrectionsOnboard",
    "http://data.europa.eu/949/qNvdriverAdhes",
    "http://data.europa.eu/949/maximumPermittedSpeed",
    "http://data.europa.eu/949/hasAdditionalBrakingInformation",
    "http://data.europa.eu/949/eddyCurrentBraking",
    "http://data.europa.eu/949/systemSeparationInfo",
    "http://data.europa.eu/949/passesThroughTunnel",
    "http://data.europa.eu/949/minimumHorizontalRadius",
    "http://data.europa.eu/949/minimumTemperature",
    "http://data.europa.eu/949/trackRaisedPantographsDistanceAndSpeed",
    "http://data.europa.eu/949/etcsNationalPacket44",
    "http://data.europa.eu/949/reasonsEtcsRadioBlockCenterReject",
    "http://data.europa.eu/949/hasLevelCrossings",
    "http://data.europa.eu/949/gsmRVersion151",
    "http://data.europa.eu/949/dNvroll",
    "http://data.europa.eu/949/automaticDroppingDeviceRequired",
    "http://data.europa.eu/949/tNvovtrp",
    "http://data.europa.eu/949/minFlangeThickness",
    "http://data.europa.eu/949/maximumAltitude",
    "http://data.europa.eu/949/specificInformation",
    "http://data.europa.eu/949/minWheelDiameter",
    "http://data.europa.eu/949/phaseSeparation",
    "http://data.europa.eu/949/dNvpotrp",
    "http://data.europa.eu/949/etcsMVersion",
    "http://data.europa.eu/949/profileNumberSemiTrailers",
    "http://data.europa.eu/949/otherCantDeficiencyBasicSSP",
    "http://data.europa.eu/949/localRulesOrRestrictions",
    "http://data.europa.eu/949/raisedPantographsDistanceAndSpeed"
])
from rdflib import URIRef, BNode

def recursively_copy(iri, source_graph, target_graph, seen):
    if iri in seen:
        return
    seen.add(iri)

    for p, o in source_graph.predicate_objects(iri):
        target_graph.add((iri, p, o))
        if isinstance(o, (URIRef, BNode)):
            recursively_copy(o, source_graph, target_graph, seen)

# Copy relevant triples
seen_nodes = set()
for iri in used_entities:
    recursively_copy(URIRef(iri), full_onto, sub_onto, seen_nodes)

# Serialize to Turtle with base and clean prefixes
sub_onto.serialize("sub_ontology.ttl", format="turtle", base=ERA)
